/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	customconfigv1 "github.com/onkarbanerjee/crd-custom-config/pkg/apis/customconfig/v1"
	versioned "github.com/onkarbanerjee/crd-custom-config/pkg/client/clientset/versioned"
	internalinterfaces "github.com/onkarbanerjee/crd-custom-config/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/onkarbanerjee/crd-custom-config/pkg/client/listers/customconfig/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CustomConfigInformer provides access to a shared informer and lister for
// CustomConfigs.
type CustomConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.CustomConfigLister
}

type customConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCustomConfigInformer constructs a new informer for CustomConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCustomConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCustomConfigInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCustomConfigInformer constructs a new informer for CustomConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCustomConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MtcilV1().CustomConfigs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MtcilV1().CustomConfigs(namespace).Watch(context.TODO(), options)
			},
		},
		&customconfigv1.CustomConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *customConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCustomConfigInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *customConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&customconfigv1.CustomConfig{}, f.defaultInformer)
}

func (f *customConfigInformer) Lister() v1.CustomConfigLister {
	return v1.NewCustomConfigLister(f.Informer().GetIndexer())
}
