/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	customconfigv1 "github.com/onkarbanerjee/crd-custom-config/pkg/apis/customconfig/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCustomConfigs implements CustomConfigInterface
type FakeCustomConfigs struct {
	Fake *FakeMtcilV1
	ns   string
}

var customconfigsResource = schema.GroupVersionResource{Group: "mtcil.com", Version: "v1", Resource: "customconfigs"}

var customconfigsKind = schema.GroupVersionKind{Group: "mtcil.com", Version: "v1", Kind: "CustomConfig"}

// Get takes name of the customConfig, and returns the corresponding customConfig object, and an error if there is any.
func (c *FakeCustomConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *customconfigv1.CustomConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(customconfigsResource, c.ns, name), &customconfigv1.CustomConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*customconfigv1.CustomConfig), err
}

// List takes label and field selectors, and returns the list of CustomConfigs that match those selectors.
func (c *FakeCustomConfigs) List(ctx context.Context, opts v1.ListOptions) (result *customconfigv1.CustomConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(customconfigsResource, customconfigsKind, c.ns, opts), &customconfigv1.CustomConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &customconfigv1.CustomConfigList{ListMeta: obj.(*customconfigv1.CustomConfigList).ListMeta}
	for _, item := range obj.(*customconfigv1.CustomConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested customConfigs.
func (c *FakeCustomConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(customconfigsResource, c.ns, opts))

}

// Create takes the representation of a customConfig and creates it.  Returns the server's representation of the customConfig, and an error, if there is any.
func (c *FakeCustomConfigs) Create(ctx context.Context, customConfig *customconfigv1.CustomConfig, opts v1.CreateOptions) (result *customconfigv1.CustomConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(customconfigsResource, c.ns, customConfig), &customconfigv1.CustomConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*customconfigv1.CustomConfig), err
}

// Update takes the representation of a customConfig and updates it. Returns the server's representation of the customConfig, and an error, if there is any.
func (c *FakeCustomConfigs) Update(ctx context.Context, customConfig *customconfigv1.CustomConfig, opts v1.UpdateOptions) (result *customconfigv1.CustomConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(customconfigsResource, c.ns, customConfig), &customconfigv1.CustomConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*customconfigv1.CustomConfig), err
}

// Delete takes name of the customConfig and deletes it. Returns an error if one occurs.
func (c *FakeCustomConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(customconfigsResource, c.ns, name), &customconfigv1.CustomConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCustomConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(customconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &customconfigv1.CustomConfigList{})
	return err
}

// Patch applies the patch and returns the patched customConfig.
func (c *FakeCustomConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *customconfigv1.CustomConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(customconfigsResource, c.ns, name, pt, data, subresources...), &customconfigv1.CustomConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*customconfigv1.CustomConfig), err
}
